{
    'gender': 'dschender',
    'Bachelor': 'bettschella',
    'Instagram': 'innßtah-gramm',
    'App': 'äpp',
    'Software': 'sofftwär',
    'Hardware': 'hahdwehr',
    'Smartphone': 'smahrthfohn',
    'Design': 'di-sein',
    'Designer': 'di-seinah',
    'Internet': 'intahnett',
    'Computer': 'kompjuta',
    'Technology': 'tek-nolo-gie',
    'Digital': 'didschital',
    'Engineer': 'endschiniehr',
    'Science': 'sains',
    'Research': 'riesöhrch',
    'Database': 'deh-tah-behs',
    'Server': 'sörvah',
    'Network': 'nett-wörk',
    'Security': 'sie-kjuri-tie',
    'Algorithm': 'algo-ritthm',
    'Analytics': 'ana-lü-tiks',
    'Artificial Intelligence': 'ah-ti-fis-chal in-tellie-gens',
    'Machine Learning': 'mä-schin lörning',
    'Deep Learning': 'diep lörning',
    'Neural Network': 'nö-ral nett-wörk',
    'Data Science': 'deh-tah sains',
    'Big Data': 'bigg deh-tah',
    'Cloud Computing': 'klaud kompjuting',
    'Virtual Reality': 'virtu-al ri-aliti',
    'Augmented Reality': 'aug-mentet ri-aliti',
    'Cybersecurity': 'saiba-sie-kjuri-tie',
    'Blockchain': 'blokk-chain',
    'Cryptocurrency': 'kripto-kur-ren-sie',
    'Bitcoin': 'bit-koin',
    'Ethereum': 'i-the-ri-um',
    'Startup': 'statt-up',
    'Entrepreneur': 'on-tre-pre-noor',
    'Innovation': 'innova-tion',
    'Disruption': 'dis-ruption',
    'Ecosystem': 'eko-sistem',
    'Platform': 'platt-form',
    'Sustainability': 'sus-tain-ability',
    'Green Technology': 'green tek-nolo-gie',
    'Renewable Energy': 'ri-nu-able en-er-gie',
    'Solar Power': 'so-lar pow-er',
    'Wind Power': 'wind pow-er',
    'Hydro Power': 'hy-dro pow-er',
    'Electric Vehicle': 'elek-tric vehi-cle',
    'Self-driving Car': 'self-dri-ving car',
    'Drone': 'drohn',
    'Robot': 'ro-bot',
    'Automation': 'auto-mation',
    'Internet of Things': 'intahnett of things',
    'Smart City': 'smahrt city',
    '5G': 'five gee',
    'WiFi': 'wai-fai',
    'Bluetooth': 'blu-tooth',
    'USB': 'you ess bee',
    'GPS': 'gee pee ess',
    'LED': 'ell ee dee',
    'LCD': 'ell see dee',
    'OLED': 'oh ell ee dee',
    'VR': 'vee ar',
    'AR': 'ay ar',
    'AI': 'ay ai',
    'ML': 'em ell',
    'DL': 'dee ell',
    'NN': 'en en',
    'DS': 'dee ess',
    'BD': 'bee dee',
    'CC': 'see see',
    'VR': 'vee ar',
    'AR': 'ay ar',
    'CS': 'see ess',
    'BC': 'bee see',
    'CC': 'see see',
    'EV': 'ee vee',
    'SDC': 'ess dee see',
    'IoT': 'ai oh tee',
    'SC': 'ess see',
    '5G': 'five gee',
    'WiFi': 'wai fai',
    'BT': 'bee tee',
    'USB': 'you ess bee',
    'GPS': 'gee pee ess',
    'LED': 'ell ee dee',
    'LCD': 'ell see dee',
    'OLED': 'oh ell ee dee',
}